let all=[],shown=[],index=0;
const $=s=>document.querySelector(s);
function repo(){let h=location.hostname,p=location.pathname.split("/").filter(Boolean);return h.endsWith(".github.io")?{o:h.split(".")[0],r:p[0]||""}:null}
async function getPhotos(){const r=repo();if(!r)return[];try{let q=await fetch(`https://api.github.com/repos/${r.o}/${r.r}/contents/photos?ref=main`);if(!q.ok)return[];let a=await q.json();return Array.isArray(a)?a.filter(x=>x.type==="file"&&/\.(jpe?g|png|webp|gif|avif)$/i.test(x.name)).sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true})):[]}catch(e){return[]}}
async function loadLogo(){const r=repo();if(!r)return;try{let q=await fetch(`https://api.github.com/repos/${r.o}/${r.r}/contents/logo/logo.png?ref=main`);if(!q.ok)return;let d=await q.json(),src=d.download_url;$(".logo").innerHTML=`<img src="${src}" alt="Логотип">`;$(".heroLogo").innerHTML=`<img src="${src}" alt="Логотип">`}catch(e){}}
function render(){let q=$("#search").value.trim().toLowerCase();shown=q?all.filter(x=>x.name.toLowerCase().includes(q)):all;$("#counter").textContent=shown.length;$("#grid").innerHTML=shown.length?shown.map((x,i)=>`<article class="card" data-i="${i}"><div class="pic"><img loading="lazy" src="${x.src}" alt="${esc(x.name)}"></div><div class="info"><h3>Будівельний матеріал</h3><p>КОНСУЛЬТАЦІЯ ТА ЗАМОВЛЕННЯ</p></div></article>`).join(""):`<div class="empty">У папці <b>photos</b> поки немає фотографій.<br>Додайте фото — сайт автоматично їх покаже.</div>`;document.querySelectorAll(".card").forEach(c=>c.onclick=()=>open(+c.dataset.i))}
function esc(s){return s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function open(i){index=i;$("#big").src=shown[index].src;$("#viewer").hidden=false}
function step(d){if(!shown.length)return;index=(index+d+shown.length)%shown.length;$("#big").src=shown[index].src}
$("#search").addEventListener("input",render);$("#close").onclick=()=>$("#viewer").hidden=true;$("#prev").onclick=()=>step(-1);$("#next").onclick=()=>step(1);$("#viewer").addEventListener("click",e=>{if(e.target.id==="viewer")$("#viewer").hidden=true});document.addEventListener("keydown",e=>{if(e.key==="Escape")$("#viewer").hidden=true;if(e.key==="ArrowLeft")step(-1);if(e.key==="ArrowRight")step(1)});
(async()=>{all=(await getPhotos()).map(x=>({src:x.download_url,name:x.name}));render();loadLogo()})();
